package ai.saniou.coreui.theme

import androidx.compose.ui.graphics.Color


// Thread 2026 UI refresh: modern reading workspace.
// Soft graphite surfaces + vivid indigo primary + teal accent.
// Tuned for long Desktop sessions; no sketchy neon / pure Material defaults.

// Light Scheme
val md_theme_light_primary = Color(0xFF4F46E5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF1E1B4B)
val md_theme_light_secondary = Color(0xFF5B6478)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8ECF5)
val md_theme_light_onSecondaryContainer = Color(0xFF171C27)
val md_theme_light_tertiary = Color(0xFF0F766E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCCFBF1)
val md_theme_light_onTertiaryContainer = Color(0xFF042F2E)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_errorContainer = Color(0xFFFEE2E2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF7F1D1D)
val md_theme_light_background = Color(0xFFF4F5F9)
val md_theme_light_onBackground = Color(0xFF111827)
val md_theme_light_surface = Color(0xFFFCFCFE)
val md_theme_light_onSurface = Color(0xFF111827)
val md_theme_light_surfaceVariant = Color(0xFFE7E9F0)
val md_theme_light_onSurfaceVariant = Color(0xFF4B5565)
val md_theme_light_outline = Color(0xFF8B93A7)
val md_theme_light_inverseOnSurface = Color(0xFFF3F4F8)
val md_theme_light_inverseSurface = Color(0xFF1F2937)
val md_theme_light_inversePrimary = Color(0xFFC7D2FE)
val md_theme_light_surfaceTint = Color(0xFF4F46E5)
val md_theme_light_outlineVariant = Color(0xFFD5DAE6)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Scheme
val md_theme_dark_primary = Color(0xFFA5B4FC)
val md_theme_dark_onPrimary = Color(0xFF1E1B4B)
val md_theme_dark_primaryContainer = Color(0xFF3730A3)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E7FF)
val md_theme_dark_secondary = Color(0xFFC5CAD8)
val md_theme_dark_onSecondary = Color(0xFF262B38)
val md_theme_dark_secondaryContainer = Color(0xFF3C4354)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8ECF5)
val md_theme_dark_tertiary = Color(0xFF5EEAD4)
val md_theme_dark_onTertiary = Color(0xFF042F2E)
val md_theme_dark_tertiaryContainer = Color(0xFF115E59)
val md_theme_dark_onTertiaryContainer = Color(0xFFCCFBF1)
val md_theme_dark_error = Color(0xFFFCA5A5)
val md_theme_dark_errorContainer = Color(0xFF991B1B)
val md_theme_dark_onError = Color(0xFF450A0A)
val md_theme_dark_onErrorContainer = Color(0xFFFEE2E2)
val md_theme_dark_background = Color(0xFF0B0F17)
val md_theme_dark_onBackground = Color(0xFFE5E7EB)
val md_theme_dark_surface = Color(0xFF121722)
val md_theme_dark_onSurface = Color(0xFFE5E7EB)
val md_theme_dark_surfaceVariant = Color(0xFF2A3140)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7CDD9)
val md_theme_dark_outline = Color(0xFF8B93A7)
val md_theme_dark_inverseOnSurface = Color(0xFF1F2937)
val md_theme_dark_inverseSurface = Color(0xFFE5E7EB)
val md_theme_dark_inversePrimary = Color(0xFF4F46E5)
val md_theme_dark_surfaceTint = Color(0xFFA5B4FC)
val md_theme_dark_outlineVariant = Color(0xFF3A4152)
val md_theme_dark_scrim = Color(0xFF000000)
