package ai.saniou.coreui.theme

import androidx.compose.ui.graphics.Color


// Thread 2026: quiet indigo surfaces with a fresh cyan accent.
// The palette is deliberately neutral enough for long reading sessions on Desktop.

// Light Scheme
val md_theme_light_primary = Color(0xFF5456D9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE4E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF17165C)
val md_theme_light_secondary = Color(0xFF596174)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE1E6F4)
val md_theme_light_onSecondaryContainer = Color(0xFF181E2B)
val md_theme_light_tertiary = Color(0xFF087F8C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBDEFF4)
val md_theme_light_onTertiaryContainer = Color(0xFF002F35)
val md_theme_light_error = Color(0xFFB42318)
val md_theme_light_errorContainer = Color(0xFFFFE1DE)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF5F0A04)
val md_theme_light_background = Color(0xFFF7F8FC)
val md_theme_light_onBackground = Color(0xFF171923)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF171923)
val md_theme_light_surfaceVariant = Color(0xFFE9EAF2)
val md_theme_light_onSurfaceVariant = Color(0xFF5D6170)
val md_theme_light_outline = Color(0xFF7A7F90)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1F7)
val md_theme_light_inverseSurface = Color(0xFF2D2F39)
val md_theme_light_inversePrimary = Color(0xFFBEC2FF)
val md_theme_light_surfaceTint = Color(0xFF5456D9)
val md_theme_light_outlineVariant = Color(0xFFD8DAE5)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Scheme
val md_theme_dark_primary = Color(0xFFBEC2FF)
val md_theme_dark_onPrimary = Color(0xFF25237E)
val md_theme_dark_primaryContainer = Color(0xFF3B3BA6)
val md_theme_dark_onPrimaryContainer = Color(0xFFE4E4FF)
val md_theme_dark_secondary = Color(0xFFC4C9D9)
val md_theme_dark_onSecondary = Color(0xFF2E3443)
val md_theme_dark_secondaryContainer = Color(0xFF454B5C)
val md_theme_dark_onSecondaryContainer = Color(0xFFE1E6F4)
val md_theme_dark_tertiary = Color(0xFF79D5DE)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF00505A)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDEFF4)
val md_theme_dark_error = Color(0xFFFFB4AC)
val md_theme_dark_errorContainer = Color(0xFF8C1D14)
val md_theme_dark_onError = Color(0xFF680C06)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF11131A)
val md_theme_dark_onBackground = Color(0xFFE5E6EE)
val md_theme_dark_surface = Color(0xFF161820)
val md_theme_dark_onSurface = Color(0xFFE5E6EE)
val md_theme_dark_surfaceVariant = Color(0xFF30333F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C7D1)
val md_theme_dark_outline = Color(0xFF9296A6)
val md_theme_dark_inverseOnSurface = Color(0xFF2D2F39)
val md_theme_dark_inverseSurface = Color(0xFFE5E6EE)
val md_theme_dark_inversePrimary = Color(0xFF5456D9)
val md_theme_dark_surfaceTint = Color(0xFFBEC2FF)
val md_theme_dark_outlineVariant = Color(0xFF414451)
val md_theme_dark_scrim = Color(0xFF000000)
